#! /bin/env bash
shopt -s lastpipe

# ---

data_file="$( realpath "$0" ).data"
source_home="$( dirname "$( realpath "$0" )" )/filesets"

# shellcheck disable=SC2002
cat "$data_file" | while read -r source_dir symlink_dir; do
	# Skip empty/incomplete lines.
	#
	[ -z "$source_dir" ] && continue
	[ -z "$symlink_dir" ] && continue

	# Skip comment lines.
	#
	[ "${source_dir:0:1}" == '#' ] && continue


	source_dir="${source_home}/${source_dir}"
	symlink_dir="${symlink_dir/'~'/${HOME}}"

	ls -1 -A "$source_dir" | while read -r item; do

		source_item="${source_dir}/${item}"
		symlink_item="${symlink_dir}/${item}"

		case "$( stat --format='%F' "$symlink_item" )" in
			# A file type of '' means the `stat` call above failed,
			# which itself means the "$symlink_item" does not exist.
			''                      ) ;;

			'fifo'                  ) exit 1 ;;
			'socket'                ) exit 1 ;;
			'block special file'    ) exit 1 ;;
			'character special file') exit 1 ;;

			'directory'             ) rm -rf "$symlink_item" ;;
			'regular file'          ) rm     "$symlink_item" ;;
			'regular empty file'    ) rm     "$symlink_item" ;;

			'symbolic link'         )
				# Do nothing if link already points to source.
				#
				source_realpath="$( realpath "$source_item" )"
				symlink_realpath="$( realpath "$symlink_item" )"
				[ "$source_realpath" == "$symlink_realpath" ] && continue
		
				rm "$symlink_item"
				;;

			*) exit 2 ;;
		esac 2> /dev/null

		# Create the symlink.
		#
		[ -d "$symlink_dir" ] || mkdir -p "$symlink_dir"
		ln -sT "$source_item" "$symlink_item"

	done

done
