#! /bin/bash
shopt -s lastpipe

# ---

# Set shell niceties.
#
shopt -s autocd checkwinsize globstar interactive_comments lastpipe no_empty_cmd_completion sourcepath


# Executable search order should be: - the current directory
#                                    - "${HOME}/bin"
#                                    - "${HOME}/bin/vendor"
#                                    - "${HOME}/.nodes/bin"
#                                    - "${HOME}/.yarn/bin"
#                                    - snap packages
#                                    - native packages
#                                    - the current directory's "./bin"
#
export PATH=".:${HOME}/bin:${HOME}/bin/vendor:${HOME}/.nodes/bin:${HOME}/.yarn/bin:/snap/bin:${PATH}:./bin"


# Helper for absolute paths to real binaries.
#
function real {
  # We want a real binary, not a possible override function, so `which` is a must.
  # shellcheck disable=SC2230
  #
  local binary="$( which "$@" )"

  realpath "$binary"
}


# Explicitly set our language and sorting collation of choice.
#
export LANG=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8


# Explicitly set our $EDITOR of choice.
#
export EDITOR="$( real hx )"
function helix { "$EDITOR" "$@" ;}
function :     { "$EDITOR" "$@" ;}


# Postgres should connect to host "postgres" by default.
# (https://www.postgresql.org/docs/current/libpq-envars.html)
#
export PGHOST='postgres'




# Set sensible tooling defaults and shortcuts.

  # bat

  # It's nice to have a 1-char name for something
  # that will properly page/colorize man/help text.
  #
  function m { man "$@" | bat --plain --language='man' ; }
  function h { "$@" --help | bat --plain --language='help' ; }


  # cd

  # Make it easier to `cd` into common locations.
  #
  export CDPATH=".:${HOME}"


  # eget

  # Make sure `eget` knows where to download binaries to
  # *and* knows where to look for existing binaries when
  # determining timestamps for `--upgrade-only` purposes.
  #
  export EGET_BIN="${HOME}/bin/vendor"


  # fzf

  fzf_keybinding_spec="ctrl-i:up,ctrl-k:down,space:toggle,ctrl-space:toggle"

  fzf_preview_command="file --brief --mime-type -- {} | starts-with? 'text/'  \
                       && bat --force-colorization --line-range='1:200' -- {} \
                       || echo '(non-text content)'"

  export FZF_DEFAULT_COMMAND="fd --hidden --exclude='.git/' --color='always'"
  export FZF_DEFAULT_OPTS="--ansi                               \
                           --cycle                              \
                           --header=''                          \
                           --info='inline'                      \
                           --keep-right                         \
                           --layout='reverse'                   \
                                                                \
                           --bind='${fzf_keybinding_spec}'      \
                                                                \
                           --preview-window='hidden'            \
                           --preview=\"${fzf_preview_command}\" "


  # git / lazygit

  function g { lazygit ;}

  function gadd        { git add                               "$@" ;}
  function gblame      { git blame -w --minimal --color-by-age "$@" ;}
  function gbranch     { git branch                            "$@" ;}
  function gcheckout   { git checkout                          "$@" ;}
  function gcherrypick { git cherry-pick                       "$@" ;}
  function gconfig     { git config                            "$@" ;}
  function gclone      { git clone                             "$@" ;}
  function gcommit     { git commit                            "$@" ;}
  function gdiff       { git diff                              "$@" ;}
  function gfetch      { git fetch                             "$@" ;}
  function ggraph      { git log --oneline --decorate --graph  "$@" ;}
  function ginit       { git init                              "$@" ;}
  function glog        { git log                               "$@" ;}
  function gmerge      { git merge --no-ff                     "$@" ;}
  function gmove       { git mv                                "$@" ;}
  function gmv         { git mv                                "$@" ;}
  function gpatch      { git apply                             "$@" ;}
  function gpop        { git stash pop                         "$@" ;}
  function gpull       { git pull                              "$@" ;}
  function gpush       { git push                              "$@" ;}
  function grebase     { git rebase                            "$@" ;}
  function gremote     { git remote                            "$@" ;}
  function greset      { git reset                             "$@" ;}
  function gstage      { git add                               "$@" ;}
  function gstash      { git stash                             "$@" ;}
  function gstatus     { git status                            "$@" ;}
  function gtag        { git tag                               "$@" ;}
  function gtrack      { git add                               "$@" ;}
  function gunchange   { git checkout HEAD                     "$@" ;}
  function gundelete   { git checkout HEAD                     "$@" ;}
  function gunstage    { git reset                             "$@" ;}
  function guntrack    { git rm -r --cached                    "$@" ;}

  function gdeploy {
    local remote="${1:-production}"
    local branch="$( gbranch --show-current )"

    gremote 2> /dev/null | has-line? "$remote" || return 1

    local confirmation
    printf 'Deploy branch "\e[33;1m%s\e[0m" to remote "\e[31;1m%s\e[0m"? (y/N) ' "$branch" "$remote"; read -r confirmation
    [ "$( tr '[:upper:]' '[:lower:]' <<< "$confirmation" )" == 'y' ] || return 2

    ding-if-slow gpush --force "$remote" "${branch}:main"
  }


  # grep

  function grep { "$( real grep )" -P --color=auto "$@" ;}


  # heroku

  function k { heroku "$@" ;}


  # lazydocker

  function lazydocker {
    command -v docker &> /dev/null || sudo apt install -qqy docker.io
    sudo "$( real lazydocker )" "$@"
  }


  # less

  function less { "$( real less )" --quit-if-one-screen --LONG-PROMPT --LINE-NUMBERS --RAW-CONTROL-CHARS --silent --chop-long-lines --shift=1 "$@" ;}


  # ls

  function f {
    # Use of `eval` here is required because we're building out the `--hide` params,
    # and is why "$@" subsequently requires special handling.

    arg_params="$( [ -n "$*" ] && printf '"%s" ' "$@" )"
    hide_params="$( xargs --arg-file="${HOME}/.hidden" --replace printf '--hide="%s" ' "{}" 2> /dev/null )"
    style_params="-ohH --color='auto' --group-directories-first --time-style='long-iso' --quoting-style='literal'"

    eval "ls ${style_params} ${hide_params} ${arg_params}"
  }
  function a { f --almost-all "$@" ;}


  # pgcli

  function pgcli { "$( real pgcli )" --pgclirc="~/.config/pgcli/config" "$@" ;}


  # rg

  function rg { "$( real rg )" --engine="pcre2" --color=auto --follow "$@" ;}


  # ... shellcheck (this comment can't look like a Shellcheck directive)

  # `shellcheck` is a bit of a pain to use on directories that
  # include both executable scripts and data files, as it generates
  # a ton of false positive warnings for the non-script files. This
  # shim filters non-files and non-executables out of the parameter
  # list.

  function shellcheck {
    declare -a args=("$@")
    declare -a executables

    for (( i=0; i < "${#args[*]}"; i++ )); do
      # We only want to run our sanity checks on non-option arguments.
      # Anything that begins with a '-' gets passed through unlatered.

      if [ "$( head -c1 <<< "${args[$i]}" )" != '-' ]; then
        [ -f "${args[$i]}" ] || continue  # Only keep files.
        [ -x "${args[$i]}" ] || starts-with? '#!' < "${args[$i]}" || continue  # Only keep script-likes.
      fi

      executables+=("${args[$i]}")
    done

    "$( real shellcheck )" "${executables[@]}"
  }


  # tree

  function list { tree -lR --dirsfirst --sort=version "$@" ;}




# Filesystem manipulation niceties.

function ...   { cd ../..       ;}
function ....  { cd ../../..    ;}
function ..... { cd ../../../.. ;}

function mkcd { mkdir -p "$1" && cd "$1"; }

function mirror {
  rsync --verbose                               \
        --recursive --force                     \
        --whole-file --delete-during            \
        --links --perms --executability --times \
        "$@"
}

function break-out-of-links {
  local pwd="$( pwd -P )"
  local link_root="${HOME}/links/home/"
  starts-with? "$link_root" <<< "$pwd" && cd "${pwd//${link_root}/~/}"
}




# Set the prompt.
#
prompt_setter="${HOME}/bin/prompt.src"
[ -r "$prompt_setter" ] && source "$prompt_setter"


# Load additional VM-specific customizations.
#
vm_customization_home="${HOME}/vm-scripts/$( hostname )"
if [ -d "$vm_customization_home" ]; then
  export PATH="${PATH}:${vm_customization_home}/bin"

  vm_customization_file="${vm_customization_home}/custom-shell"
  [ -r "$vm_customization_file" ] && source "$vm_customization_file"
fi


# Load Dev-specific tooling (ENV/language helpers).
#
export DEV_ROOT="${HOME}/dev"
dev_helpers="${HOME}/bin/dev.src"
[ -r "$dev_helpers" ] && source "$dev_helpers"


# Ensure all of the above-defined functions are usable in subshells as well.
#
export -f ... .... ..... :                                                          \
          a break-out-of-links f g gadd gblame gbranch gcheckout gcherrypick gclone \
          gcommit gconfig gdeploy gdiff gfetch ggraph ginit glog gmerge gmove gmv   \
          gpatch gpop gpull gpush grebase gremote grep greset gstage gstash gstatus \
          gtag gtrack gunchange gundelete gunstage guntrack h helix k lazydocker    \
          less list m mirror mkcd pgcli real rg shellcheck


# New windows/panes opened from within a symlinked location will show up within ~/links,
# so we're breaking out of those by default on new shells to avoid having to do it manually.
#
break-out-of-links


true  # Never start a shell with a non-0 status on the prompt.
