#! /bin/env bash

[ -n "$PS1"            ] || return # Exit unless interactive.
[ -n "$_byobu_sourced" ] || return # Exit unless within a Byobu session.

# ---


# Set shell behaviours.
#
shopt -s autocd checkwinsize globstar interactive_comments lastpipe no_empty_cmd_completion sourcepath

# Set command history behaviours.
#
set +H # Disable history expansion ("!" usage).
shopt -s histappend # Append to the history file.
#
export HISTCONTROL='ignorespace:ignoredups'
export HISTFILESIZE='20'
export HISTSIZE='20'


# Check for window changes and update $LINES/$COLUMNS as needed.
#
shopt -s checkwinsize


# ---


# Helper for absolute paths to real binaries.
#
function real {
  # We want a real binary, so `which` is a must.
  # shellcheck disable=SC2230
  #
  local binary="$( which "$@" )"

  realpath "$binary"
}


# Though the system only supports 256 color,
# setting $COLORTERM gives faster text rendering.
#
export COLORTERM='truecolor'


# Explicitly set our language and sorting collation of choice.
#
export LANG='en_US.UTF-8'
export LC_COLLATE='en_US.UTF-8'


# Explicitly set our $EDITOR of choice.
#
export EDITOR="$( real hx )"
function helix { "$EDITOR" "$@" ;}
function e     { "$EDITOR" "$@" ;}


# Surface web content via our own `browser` helper.
#
export BROWSER="${HOME}/bin/browser"


# Postgres should connect to host "postgres" by default.
# (https://www.postgresql.org/docs/current/libpq-envars.html)
#
export PGHOST='postgres'


# Make it easier to navigate from a location under
# "~/links/home" to where it actually resides in the filesystem.
#
function break-out-of-links {
  local pwd="$( pwd -P )"
  local link_root="${HOME}/links/filesets/home/"
  'starts-with?' "$link_root" <<< "$pwd" && cd "${pwd//${link_root}/${HOME}/}"
}


# Filesystem navigation niceties.
#
function -     { cd -           ;}
#
function ...   { cd ../..       ;}
function ....  { cd ../../..    ;}
function ..... { cd ../../../.. ;}
#
function mkcd { mkdir -p "$1" && cd "$1" ;}


# Helpers for re-running commands until successful.
#
function !! {
  local backoff='1'
  'integer?' "$1" && backoff="$1" && shift

  until "$@"; do sleep "$backoff"; done
}
#
function !0 { '!!' 0 "$@" ;}
function !1 { '!!' 1 "$@" ;}
function !5 { '!!' 5 "$@" ;}


# Make it easier to mirror one location into another.
#
function mirror {
  local usage='Usage: mirror [SOURCE] [AS]'
  printf '%s\n' -- "$@" | grep -x --quiet -- '--help' && echo "$usage" && return 0

  local source="${1%/}/" && shift
  local destination="${1%/}" && shift
  { [ -z "$source" ] || [ -z "$destination" ] || [ "$#" != 0 ] ;} && echo "$usage" && return 1

  [ -e "$destination" ] || mkdir -p "$destination" || return 2

  rsync --verbose                               \
        --recursive --force                     \
        --whole-file --delete-during            \
        --links --perms --executability --times \
        "$source" "$destination"
}


# Make it easier to peek into a data stream as it's piped from one tool to another.
#
function peek { tee /dev/tty ;}


# ---


# Set sensible tooling defaults and shortcuts.

  # at

  # `after 5 minutes <<< "command"`
  #
  function after { at now + "$@" &> /dev/null ;}

  # `whenever <<< "command"`
  #
  function whenever { at -q &> /dev/null ;}


  # bat

  # It's nice to have a 1-char name for something
  # that will properly page/colorize help/manpage text.
  #
  function h { PAGER='cat' "$@" --help | bat --plain --language='help' --chop-long-lines ;}
  function m { PAGER='cat' man "$@"    | bat --plain --language='man'                    ;}

  # Allow for easy STDIN tailing with highlighting.
  # (So we can easily `tail -f [FILE]` into `bat`.)
  #
  function fbat {
    printf '%s\n' -- "$@" | grep -x --quiet -- '--help' && echo 'Usage: fbat [LANGUAGE] [BAT_OPTIONS]' && return 0

    local language
    [ -n "$1" ] && ! 'starts-with?' -- '--' <<< "$1" && language="$1" && shift
    bat --paging='never' --language="${language:-txt}" "$@"
  }

  # Paging while retaining header lines is a common
  # enough need that we want to accomodate it easily.
  #
  function hbat {
    printf '%s\n' -- "$@" | grep -x --quiet -- '--help' && echo 'Usage: hbat [HEADER_HEIGHT] [BAT_OPTIONS]' && return 0

    # Ensure we have a header-compatible `less`.
    #
    less_version="$( less --version | head -n1 | cut -d' ' -f2 | grep -P --only-matching '^[0-9]+' )"
    [ "$less_version" -ge 663 ] || "${HOME}/bin/builds/less-663/plug"

    local header_height='1'
    'integer?' "$1" && header_height="$1" && shift
    LESS="${LESS} --header=${header_height}" bat "$@"
  }


  # bw

  # The default `bw` data directory is
  # "~/.config/Bitwarden CLI", which... yikes.
  #
  export BITWARDENCLI_APPDATA_DIR="${HOME}/.config/bw"

  # Wrap all `bw` calls so we can automatically
  # append an active session key to the request.
  #
  function bw { "$( real bw )" --session="$( creds bitwarden/session-key )" "$@" ;}


  # cd

  # Make it easier to `cd` into common locations.
  #
  export CDPATH=".:${HOME}:${HOME}/docs"


  # croc

  # Dead-simple "send/receive" function pair that uses
  # *simple passphrases* (using only 2 *commonly-used* words).

  function send {
    wordlist_url='https://raw.githubusercontent.com/bitcoin/bips/refs/heads/master/bip-0039/english.txt'
    passphrase="$( curl --silent "$wordlist_url" | shuf -n2 | paste --serial --delimiter='-' )"

    # All `croc` output is on STDERR (🤦) and we want custom instruction text, so `awk` to the rescue.
    #
    CROC_SECRET="$passphrase" croc send "$@" 2> >( awk "NR==1; NR==2 { print \"Receive on target system via 'receive ${passphrase}'.\" }; NR >= 9" )
  }

  function receive {
    local old_ifs="$IFS"; IFS='-'
    passphrase="$*"
    IFS="$old_ifs"

    CROC_SECRET="$passphrase" croc --yes
  }


  # docker

  # Make `docker` easier to use by:
  # - lazy-installing the `docker` binary
  # - lazy-installing plugins (eg `compose`)
  # - supporting custom subcommand aliases (eg `ls`)
  # - providing an interactive console (as `docker console`)
  #
  function docker {
    # Ensure `docker`.
    #
    real docker &> /dev/null || { sudo apt install -qqy docker.io && echo ;} || return 1
    local docker_binary="$( real docker )"

    # Pass empty requests through to the binary.
    #
    [ "$#" == 0 ] && { "$docker_binary"; return ;}

    # Process subcommand (so we can lazy-install plugins as needed and process custom aliases).
    #
    local subcommand="$1" && shift
    case "$subcommand" in

      # Lazy installers for plugins.

      (buildx|build)
        # Ensure the "docker-buildx" plugin is available.
        # See: https://github.com/docker/buildx#manual-download
        #
        local docker_buildx_binary="${HOME}/.docker/cli-plugins/docker-buildx"
        [ -x "$docker_buildx_binary" ] || eget --quiet 'docker/buildx' --asset='^.json' --to="$docker_buildx_binary" || return 1

        "$docker_binary" "$subcommand" "$@"
        ;;

      (compose)
        # Ensure the "docker-compose" plugin is available.
        # See: https://docs.docker.com/compose/install/linux/
        #
        local docker_compose_binary="${HOME}/.docker/cli-plugins/docker-compose"
        [ -x "$docker_compose_binary" ] || eget --quiet 'docker/compose' --asset='^.json' --to="$docker_compose_binary" || return 1

        "$docker_binary" compose "$@"
        ;;

      # Aliases.

      (c    ) "$docker_binary" container    "$@" ;;
      (i    ) "$docker_binary" image        "$@" ;;
      (n    ) "$docker_binary" network      "$@" ;;
      (v    ) "$docker_binary" volume       "$@" ;;

      (ls   ) "$docker_binary" container ls "$@" ;;
      (prune) "$docker_binary" system prune "$@" ;;

      # Interactive console.
      #
      (console)
        local docker_history="${HOME}/.docker_history"
        history -w && history -c && history -r "$docker_history"
        while read -e -r -p '(docker) > ' -a line; do
          # Allow for empty lines.
          #
          [ -n "${line[*]}" ] || continue

          case "${line[0]}" in
            (exit) break ;;
            (h|help) h docker "${line[@]:1}" ;;
            (console) echo '* Already in console mode.' ;;

            *)
              echo "${line[*]}" >> "$docker_history"
              history -n "$docker_history"
              docker "${line[@]}"
              ;;
          esac
          echo
        done
        history -c && history -r
        ;;

      # Everything else passes through unaltered.
      #
      *) "$docker_binary" "$subcommand" "$@" ;;
    esac
  }


  # eget

  # Make sure `eget` knows where to download binaries to
  # *and* knows where to look for existing binaries when
  # determining timestamps for `--upgrade-only` purposes.
  #
  export EGET_BIN="${HOME}/bin/vendor"


  # eza

  function f {
    # shellcheck disable=SC2002
    # This is not in fact a "useless `cat`" -- it's needed to prevent STDERR output if a "~/.hidden" file does not exist.
    #
    local hide_globs="$( cat "${HOME}/.hidden" 2> /dev/null | paste -s --delimiters='|' )"

    eza --icons --long --color='always' --group-directories-first --group --smart-group --time-style='long-iso' --show-symlinks --no-quotes --ignore-glob="${hide_globs:-|}" "$@"
  }

  function a { f --almost-all --ignore-glob='|' "$@" ;}

  function list  { f --tree --git-ignore "$@" ;}
  function list+ { f --tree              "$@" ;}


  # fc

  # Easily redo/re-run history items without reaching for arrow keys.
  #
  # Runnable as-is (to redo the most recent command) or with a param,
  # which will redo the most recent command prefixed by the given value.
  #
  function redo { fc -s "$@" ;}


  # gcc

  # Colorize warnings/errors.
  #
  export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


  # geol

  function eol { geol product extended --log-level='warn' "$@" 2> /dev/null ;}


  # git / lazygit

  function g { lazygit "$@" ;}

  # Load `git` helpers.
  #
  git_helpers="${HOME}/bin/git-helpers.src"
  [ -r "$git_helpers" ] && source "$git_helpers"


  # heroku

  function k { heroku "$@" ;}

  # Disable telemetry reporting.
  #
  export DISABLE_TELEMETRY='true'


  # hexyl

  function hex { hexyl --border='none' "$@" | bat ;}


  # jq

  # Set `jq` colors to match `irb` data.
  #
  export JQ_COLORS='1;31:1;31:1;32:1;34:0;33:0;39:0;39:0;39'


  # lazydocker

  function lazydocker {
    # Ensure `docker` (via our own shim, define above).
    #
    docker version &> /dev/null || return 1

    "$( real lazydocker )" "$@"
  }


  # less

  # Allow use of `less` with non-plaintext data.
  # (See `lesspipe` manpage for additional info.)
  #
  eval "$( lesspipe )"

  # `less` (and pager use in general) should allow
  # "smart case" searches, pass color codes through
  # without mangling, and never ring the terminal bell.
  #
  export LESS='--ignore-case --raw-control-chars --silent'

  # Set sensible default when manually invoked from a shell.
  #
  function less {
    "$( real less )" --LINE-NUMBERS --chop-long-lines                  \
                     --LONG-PROMPT --shift='1' --quit-if-one-screen "$@"
  }


  # pipx

  function pipx {
    # Ensure `pipx`.
    #
    real pipx &> /dev/null || { sudo apt install -qqy pipx && echo ;} || return 1

    "$( real pipx )" "$@"
  }


  # posting

  function posting {
    # Ensure `posting` (via pipx).
    # See: https://github.com/darrenburns/posting
    #
    real posting &> /dev/null || pipx install posting || return 1

    "$( real posting )" "$@"
  }


  # rg

  function rg { "$( real rg )" --engine="pcre2" --color=auto --follow "$@" ;}


  # ... shellcheck (this comment can't look like a Shellcheck directive)

  # `shellcheck` is a bit of a pain to use on directories that
  # include both executable scripts and data files, as it generates
  # a ton of false positive warnings for the non-script files. This
  # shim filters non-files and non-executables out of the parameter
  # list.

  function shellcheck {
    declare -a args=("$@")
    declare -a executables

    for (( i=0; i < "${#args[*]}"; i++ )); do
      # We only want to run our sanity checks on non-option arguments.
      # Anything that begins with a '-' gets passed through unlatered.

      if [ "$( head -c1 <<< "${args[$i]}" )" != '-' ]; then
        [ -f "${args[$i]}" ] || continue  # Only keep files.
        [ -x "${args[$i]}" ] || { head -n1 "${args[$i]}" | grep -P --quiet '^#!.*\b(bash|sh)\b' ;} || continue  # Only keep script-likes.
      fi

      executables+=("${args[$i]}")
    done

    "$( real shellcheck )" "${executables[@]}"
  }


  # wut

  function wut {
    # Ensure `wut-cli` (via pipx).
    # See: https://github.com/shobrook/wut
    #
    # Note the lazy-install must be silent (unless something goes wrong)
    # or `wut` will unhelpfully explain that we've just installed `wut`.  🤦
    #
    if ! real wut &> /dev/null; then
      local installer_output
      if ! installer_output="$( pipx install wut-cli 2>&1 )"; then
        echo "$installer_output"
        return 1
      fi
    fi

    OPENAI_BASE_URL='https://generativelanguage.googleapis.com/v1beta/openai' \
    OPENAI_API_KEY="$( creds gemini/api-key )"                                \
    OPENAI_MODEL='gemini-3.1-flash-lite'                                      \
    "$( real wut )" "$@"
  }
  function wut? { wut "$@" ;}


# ---


# Ensure a clean pane title when under `tmux`.
#
tmux select-pane -T '' &> /dev/null


# Set the prompt.
#
prompt_setter="${HOME}/bin/set-prompt.src"
[ -r "$prompt_setter" ] && source "$prompt_setter"


# Load command completion data.
#
completion_loader='/usr/share/bash-completion/bash_completion'
[ -r "$completion_loader" ] && source "$completion_loader"


# Load additional VM-specific customizations.
#
vm_customization_file="${HOME}/vm-scripts/$( hostname --short )/custom-shell"
[ -r "$vm_customization_file" ] && source "$vm_customization_file"


# Load Dev-specific tooling (ENV/language helpers).
#
export DEV_ROOT="${HOME}/dev"
dev_helpers="${HOME}/bin/dev.src"
[ -r "$dev_helpers" ] && source "$dev_helpers"


# ---


# Ensure all of the above-defined functions are usable in subshells as well.
#
export -f -- - ... .... ..... !! !0 !1 !5                                      \
          a after break-out-of-links bw docker e eol f fbat g h hbat helix hex \
          k lazydocker less list list+ m mirror mkcd peek pipx posting real    \
          receive redo rg send shellcheck wut wut?


# New windows/panes opened from within a symlinked location will show up within "~/links",
# so we're breaking out of those by default on new shells to avoid having to do it manually.
#
break-out-of-links


true  # Never start a shell with a non-0 status on the prompt.
