# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:

  authorColors:
    'Nestor Custodio': 'yellow'
    '*': 'white'
  branchColors:
    'main': 'red'
    'master': 'red'
    'staging': 'green'
    'nlc': 'yellow'
    '*': 'white'
  branchColorPatterns: {}
  customIcons:
    filenames: {}
    extensions: {}

  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: 'margin'
  tabWidth: 4
  mouseEvents: true

  skipAmendWarning: false
  skipDiscardChangeWarning: false
  skipStashWarning: true
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: true
  skipSwitchWorktreeOnCheckoutWarning: false

  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  shrinkSidePanelsToContent: true
  sidePanels:
    - ['status']
    - ['files', 'worktrees']
    - ['branches', 'remotes']
    - ['commits', 'tags', 'reflog']
    - ['stash']
  mainPanelSplitMode: 'flexible'
  enlargedSideViewLocation: 'top'
  wrapLinesInStagingView: false
  useHunkModeInStagingView: true
  language: 'auto'
  timeFormat: '2006-01-02'
  shortTimeFormat: '15:04'

  theme:
    activeBorderColor:
      - 'red'
      - 'bold'
    inactiveBorderColor:
      - 'white'
    searchingActiveBorderColor:
      - 'cyan'
      - 'bold'
    optionsTextColor:
      - 'cyan'
    selectedLineBgColor:
      - 'blue'
    inactiveViewSelectedLineBgColor:
      - 'bold'
    cherryPickedCommitFgColor:
      - 'blue'
    cherryPickedCommitBgColor:
      - 'cyan'
    markedBaseCommitFgColor:
      - 'blue'
    markedBaseCommitBgColor:
      - 'yellow'
    unstagedChangesColor:
      - 'red'
    defaultFgColor:
      - 'default'

  commitLength:
    show: true

  showListFooter: false
  showFileTree: true
  showRootItemInFileTree: true
  fileTreeSortOrder: 'foldersFirst'
  fileTreeSortCaseSensitive: true
  showNumstatInFilesView: false
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false
  showIcons: true
  nerdFontsVersion: '3'
  showFileIcons: true
  commitAuthorShortLength: 2
  commitAuthorLongLength: 17
  commitHashLength: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: 'arrowAndNumber'
  commandLogSize: 8
  splitDiff: 'auto'
  screenMode: 'normal'
  border: 'rounded'
  animateExplosion: true
  portraitMode: 'auto'
  portraitModeAutoMaxWidth: 84
  portraitModeAutoMinHeight: 46
  filterMode: 'fuzzy'

  spinner:
    frames:
      - '⠏'
      - '⠏'
      - '⠛'
      - '⠛'
      - '⠹'
      - '⠹'
      - '⠼'
      - '⠼'
      - '⠶'
      - '⠶'
      - '⠧'
      - '⠧'
    rate: 50

  statusPanelView: 'allBranchesLog'
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: true
  switchTabsWithPanelJumpKeys: false


git:


  pagers:
    - colorArg: 'always'
      pager: "delta --true-color='never' --dark --line-numbers --line-numbers-left-format='{nm:^4}:' --hunk-header-style='syntax' --paging='never'"
      externalDiffCommand: ''
      useExternalDiffGitConfig: false
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  merging:
    manualCommit: false
    args: ''
    squashMergeMessage: 'squash: {{selectedRef}} -> {{currentBranch}}'

  mainBranches:
    - 'main'
    - 'master'

  skipHookPrefix: 'WIP'
  autoFetch: true
  autoRefresh: true
  autoDetectExternalChanges: true
  autoForwardBranches: 'onlyMainBranches'
  fetchAll: false
  autoStageResolvedConflicts: true
  branchLogCmd: 'git log --color=always --decorate --graph {{branchName}} --'
  allBranchesLogCmds: ['git log --color=always --decorate --graph --all --oneline --']
  ignoreWhitespaceInDiffView: false
  diffContextSize: 3
  renameSimilarityThreshold: 50
  overrideGpg: false
  disableForcePushing: false
  commitPrefix: []
  commitPrefixes: {}
  branchPrefix: ''
  parseEmoji: false

  log:
    order: 'topo-order'
    showGraph: 'always'
    showWholeGraph: false

  localBranchSortOrder: 'date'
  remoteBranchSortOrder: 'date'
  truncateCopiedCommitHashesTo: 12


worktree:
  defaultPath: ''


update:
  method: 'never'
  days: 14


refresher:
  refreshInterval: 10
  fetchInterval: 60
  externalChangeCheckInterval: 10


confirmOnQuit: false
quitOnTopLevelReturn: false


os:

  edit: ''
  editAtLine: ''
  editAtLineAndWait: ''
  editInTerminal: false
  openDirInEditor: ''
  editPreset: 'helix'
  open: ''
  openLink: ''
  copyToClipboardCmd: 'copy {{text}}'
  readFromClipboardCmd: ''
  shellFunctionsFile: ''


disableStartupPopups: true
customCommands: []
services: {}
notARepository: 'quit'
promptToReturnFromSubprocess: false


# ---


# Allowed keybindings:
#
# [ all stand-alone key presses (a-z, A-Z, 0-9, and symbols) ]
#
# <f1> / <f2> / <f3> / <f4> / <f5> / <f6> / <f7> / <f8> / <f9> / <f10> / <f11> / <f12>
# <insert> / <delete> / <home> / <end> / <pgup> / <pgdown>
# <up> / <down> / <left> / <right>
# <esc> / <tab> / <enter> / <space> / <backspace>
# <disabled>
#
# <[ctrl+][shift+]{one of the above}>
#
#
# Keybindings may also be defined as an array of the above, including an empty array in lieu of `<disabled>`.
#
#
keybinding:

  universal:
    quit-alt1: []            # Droppable once https://github.com/jesseduffield/lazygit/issues/5763
    prevItem-alt: []         # is resolved.
    nextItem-alt: []         #
    gotoTop-alt: []          #
    gotoBottom-alt: []       #
    prevBlock-alt: []        #
    nextBlock-alt: []        #
    prevBlock-alt2: []       #
    nextBlock-alt2: []       #
    confirmInEditor-alt: []  #
    scrollUpMain-alt1: []    #
    scrollDownMain-alt1: []  #
    scrollUpMain-alt2: []    #
    scrollDownMain-alt2: []  #
    diffingMenu-alt: []      #

    quit: 'q'
    suspendApp: '<ctrl+z>'
    return: '<esc>'
    quitWithoutChangingDirectory: []
    togglePanel: '<tab>'
    prevItem: 'i'
    nextItem: 'k'
    prevPage: 'I'
    nextPage: 'K'
    scrollLeft: 'j'
    scrollRight: 'l'
    gotoTop: '['
    gotoBottom: ']'
    toggleRangeSelect: ':'
    rangeSelectDown: []
    rangeSelectUp: []
    prevBlock: []
    nextBlock: []
    jumpToBlock:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
    focusMainView: 'm'
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    moveWordLeft: []
    moveWordRight: []
    backspaceWord: []
    forwardDeleteWord: []
    optionMenu: '?'
    select: '<enter>'
    goInto: '<space>'
    confirm: '<enter>'
    confirmMenu: '<enter>'
    confirmSuggestion: '<enter>'
    confirmInEditor: []
    remove: 'd'
    new: 'n'
    newWorktree: []
    edit: 'e'
    openFile: []
    scrollUpMain: '<up>'
    scrollDownMain: '<down>'
    executeShellCommand: []
    createRebaseOptionsMenu: '!'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: '<ctrl+r>'
    createPatchOptionsMenu: []
    nextTab: 'o'
    prevTab: 'u'
    nextScreenMode: '='
    prevScreenMode: '-'
    cyclePagers: []
    cyclePagersReverse: []
    undo: 'z'
    redo: 'y'
    filteringMenu: 'h'
    diffingMenu: []
    copyToClipboard: '<ctrl+c>'
    openRecentRepos: []
    submitEditorText: '<enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: 'W'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
    increaseRenameSimilarityThreshold: []
    decreaseRenameSimilarityThreshold: []
    openDiffTool: []
    editConfig: []

  status:
    checkForUpdate: []
    recentRepos: []
    allBranchesLogGraph: []
    allBranchesLogGraphReverse: []

  files:
    commitChanges: 'c'
    commitChangesWithoutHook: []
    amendLastCommit: 'a'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: []
    confirmDiscard: []
    ignoreFile: 'x'
    refreshFiles: []
    stashAllChanges: []
    viewStashOptions: 's'
    toggleStagedAll: '*'
    viewResetOptions: 'r'
    fetch: []
    toggleTreeView: 't'
    openMergeOptions: []
    openStatusFilter: 'f'
    copyFileInfoToClipboard: '<ctrl+c>'
    collapseAll: '-'
    expandAll: '+'

  branches:
    createPullRequest: []
    viewPullRequestOptions: 'g'
    openPullRequestInBrowser: []
    copyPullRequestURL: []
    checkoutBranchByName: 'c'
    forceCheckoutBranch: []
    checkoutPreviousBranch: []
    rebaseBranch: 'R'
    renameBranch: 'r'
    mergeIntoCurrentBranch: []
    moveCommitsToNewBranch: []
    viewGitFlowOptions: []
    fastForward: []
    createTag: 't'
    pushTag: 'T'
    setUpstream: 'u'
    fetchRemote: 'f'
    addForkRemote: []
    sortOrder: []

  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: []
    viewResetOptions: []
    markCommitAsFixup: 'f'
    setFixupMessage: []
    createFixupCommit: []
    squashAboveCommits: []
    moveDownCommit: '<ctrl+k>'
    moveUpCommit: '<tab>' # <-- really a mapping to '<ctrl+i>'
    amendToCommit: 'a'
    resetCommitAuthor: []
    pickCommit: 'p'
    revertCommit: 'x'
    cherryPickCopy: 'c'
    pasteCommits: 'v'
    markCommitAsBaseForRebase: 'b'
    tagCommit: 't'
    checkoutCommit: '<enter>'
    resetCherryPick: '<esc>'
    copyCommitAttributeToClipboard: '<ctrl+c>'
    openLogMenu: []
    openInBrowser: []
    openPullRequestInBrowser: []
    viewBisectOptions: []
    startInteractiveRebase: 'i'
    selectCommitsOfCurrentBranch: '*'

  amendAttribute:
    resetAuthor: []
    setAuthor: []
    addCoAuthor: []

  stash:
    popStash: 'p'
    renameStash: 'r'

  commitFiles:
    checkoutCommitFile: '<enter>'

  main:
    prevHunk: 'i'
    nextHunk: 'k'
    toggleSelectHunk: 'g'
    pickBothHunks: 'b'
    editSelectHunk: 'e'

  submodules:
    init: []
    update: []
    bulkMenu: []

  commitMessage:
    commitMenu: []
