
# Config spec at:
# https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md

# ---


reporting: 'undetermined'


# ---


gui:
  scrollHeight: 2
  expandFocusedSidePanel: true

  theme:
    activeBorderColor:
      - 'red'
      - 'bold'
    inactiveBorderColor:
      - 'white'
    optionsTextColor:
      - 'blue'


logs:
  timestamps: true
  since: ''
  tail: 500


update:
  dockerRefreshInterval: '100ms'


oS:
  openCommand: 'sh -c "xdg-open {{filename}} > /dev/null"'
  openLinkCommand: 'sh -c "xdg-open {{link}} > /dev/null"'


stats:
  maxDuration: '3m0s'
  graphs:
    - caption: 'CPU (%)'
      statPath: 'DerivedStats.CPUPercentage'
      color: 'cyan'
    - caption: 'Memory (%)'
      statPath: 'DerivedStats.MemoryPercentage'
      color: 'green'
