# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html
# Source new blocks from the base language config: https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "erb"
file-types = ["erb", "inky"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "hx.formatter", args = ["javascript"] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "hx.formatter", args = ["jsx"] }

[[language]]
name = "json"
auto-format = false
file-types = ["json", "pjson"]

[[language]]
name = "ruby"
auto-format = true
config = { solargraph = { diagnostics = true, formatting = true } }
formatter = { command = "hx.formatter", args = ["ruby"] }

[[language]]
name = "sql"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
auto-format = false
