# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html
# Source new blocks from the base language config: https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "env"
file-types = [".env", ".env.*", ".envrc"]

[[language]]
name = "erb"
file-types = ["erb", "inky"]
roots = [".ruby-version", "Gemfile", "Gemfile.lock"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "hx.formatter", args = ["javascript"] }
roots = [".node-version", "package.json", "yarn.lock"]

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "hx.formatter", args = ["jsx"] }
roots = [".node-version", "package.json", "yarn.lock"]

[[language]]
name = "json"
auto-format = false

[[language]]
name = "ruby"
auto-format = true
formatter = { command = "hx.formatter", args = ["ruby"] }
roots = [".ruby-version", "Gemfile", "Gemfile.lock"]

[[language]]
name = "sql"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
auto-format = false
