# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html

[[language]]
name = "ruby"
indent = { tab-width = 2, unit = "  " }
config = { solargraph = { diagnostics = true, formatting = true } }
formatter = { command = "hx.linter", args = ["ruby"] }
auto-format = true

[[language]]
name = "json"
auto-format = false

[[language]]
name = "yaml"
auto-format = false
